import 'package:flutter/material.dart';

class LocalizationProvider extends ChangeNotifier {
  String _locale = 'en'; // 'en' or 'si'

  String get locale => _locale;

  void toggleLocale() {
    _locale = _locale == 'en' ? 'si' : 'en';
    notifyListeners();
  }

  void setLocale(String langCode) {
    if (_locale != langCode) {
      _locale = langCode;
      notifyListeners();
    }
  }

  String translate(String key) {
    return _translations[_locale]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'home': 'Home',
      'scan': 'Scan',
      'history': 'History',
      'support': 'Support',
      'healthy': 'Healthy',
      'root_wilt': 'Root Wilt',
      'bud_rot': 'Bud Rot',
      'leaf_spot': 'Leaf Spot',
      'lethal_yellowing': 'Lethal Yellowing',
      'confidence': 'Confidence score',
      'predicted_disease': 'Predicted disease name',
      'detected': 'detected',
      'no_active_plan': 'No active treatment plan',
      'scan_leaf_start': 'Scan a coconut leaf to detect diseases and start a personalized treatment plan.',
      'scan_leaf_now': 'Scan a Leaf Now',
      'analysis_overview': 'Analysis Overview',
      'recent_scans': 'Recent Scans',
      'delete': 'Delete',
      'are_you_sure': 'Are you sure?',
      'cancel': 'Cancel',
      'confirm_delete': 'Do you want to delete this scan record?',
      'yes': 'Yes',
      'app_name': 'Cocolytics',
      'greeting': 'Hello',
      'change_language': 'म/A Change Language',
      'community': 'Community',
      'ask_ai': 'Ask AI',
      'ask_cocolytics_ai': 'Ask Cocolytics AI',
      'get_ai_answer': 'Get AI Answer',
      'ai_answer': 'AI Answer',
      'listen': 'Listen',
      'stop': 'Stop',
      'ask_again': 'Ask again',
      'ask_community': 'Ask Community',
      'post_question': 'Post a question',
      'post': 'Post',
      'no_posts_yet': 'No posts yet. Ask a question to start the community.',
      'common_symptoms': 'Common Symptoms',
      'treatments': 'Treatments',
      'logout': 'Logout',
      'botanical_name': 'Botanical Name',
      'scientific_name': 'Scientific Name',
      'plant_health': 'Plant Health',
      'no_treatment_data': 'No treatment data available',
      'profile': 'Profile',
      'home_summary': 'Here\'s your farm health summary',
      'total': 'total',
      'cases_in': 'cases in',
      'districts_reporting': 'districts reporting',
      'pending_actions': 'Pending Actions',
      'steps_to_complete': 'Steps to complete',
      'active_treatment_plan': 'Active Treatment Plan',
      'view_all': 'View all',
      'steps_done': 'steps done',
      'complete': 'complete',
      'what_to_do_next': 'What to do next',
      'more_steps_roadmap': 'more steps in roadmap',
      'how_can_we_help': 'How can we help?',
      'search_topics': 'Search topics, FAQs, experts...',
      'government_hotline': 'Government Hotline',
      'contact_state_agri': 'Contact state agricultural department',
      'expert_consultation': 'Expert Consultation',
      'chat_with_pathologists': 'Chat with plant pathologists',
      'technical_support': 'Technical Support',
      'app_issues': 'App issues & scanner calibration',
      'agricultural_centers': 'Agricultural Centers',
      'agri_centers_count': 'centers',
      'all': 'All',
      'short_term': 'Short-Term Solutions',
      'prevention_tips': 'Prevention Tips',
      'chemical_action': 'Immediate Chemical Action',
      'long_term': 'Long-Term Solutions',
      'save_plan': 'Save as My Treatment Plan',
      'view_roadmap': 'View My Treatment Roadmap',
      'use': 'Use',
      'where_to_buy': 'Where to buy',
      'how_to_use': 'How to use this chemical',
      'replace_plan': 'Replace existing plan?',
      'district_risk': 'District Risk',
      'current_severity': 'Current Severity',
      'top_disease': 'Top Disease (Country)',
      'national_stats': 'National Scan Stats',
      'no_active_alerts': 'No active alerts',
      'no_active_case': 'No active case',
      'latest_detected': 'Latest detected level',
      'waiting_scan': 'Waiting for scan data',
      'no_cases_yet': 'No cases yet',
      'no_affected_districts': 'No affected districts',
      'all_clear': 'All clear',
      // Treatments - Bud Rot
      'Immediately remove and destroy the infected bud tissues.': 'Immediately remove and destroy the infected bud tissues.',
      'Apply Bordeaux mixture or copper oxychloride paste to the cut surface.': 'Apply Bordeaux mixture or copper oxychloride paste to the cut surface.',
      'Provide good drainage to reduce humidity around the palm.': 'Provide good drainage to reduce humidity around the palm.',
      'Copper Oxychloride': 'Copper Oxychloride',
      'Apply as a paste on the affected crown or spray 1% Bordeaux mixture.': 'Apply as a paste on the affected crown or spray 1% Bordeaux mixture.',
      'Local agricultural stores': 'Local agricultural stores',
      'Farm chem suppliers': 'Farm chem suppliers',
      'Regularly inspect neighboring palms for early detection.': 'Regularly inspect neighboring palms for early detection.',
      'Ensure proper plant spacing for air circulation.': 'Ensure proper plant spacing for air circulation.',
      'Avoid physical damage to the palm bud during harvesting.': 'Avoid physical damage to the palm bud during harvesting.',
      // Lethal Yellowing
      'Quarantine the affected area immediately.': 'Quarantine the affected area immediately.',
      'Fell and burn actively infected palms to prevent insect vector spread.': 'Fell and burn actively infected palms to prevent insect vector spread.',
      'Oxytetracycline HCl': 'Oxytetracycline HCl',
      'Trunk injection (antibiotic) for temporary suppression of symptoms. Note: Not a cure.': 'Trunk injection (antibiotic) for temporary suppression of symptoms. Note: Not a cure.',
      'Certified agricultural antibiotic distributors': 'Certified agricultural antibiotic distributors',
      'Replant with resistant or highly tolerant coconut varieties (e.g., Malayan Dwarf).': 'Replant with resistant or highly tolerant coconut varieties (e.g., Malayan Dwarf).',
      'Control populations of the planthopper vector.': 'Control populations of the planthopper vector.',
      // Root Wilt
      'Cut and remove severely diseased palms showing yellowing and flaccidity.': 'Cut and remove severely diseased palms showing yellowing and flaccidity.',
      'Apply organic manure (50 kg) mixed with bio-fertilizers per palm.': 'Apply organic manure (50 kg) mixed with bio-fertilizers per palm.',
      'NPK + Magnesium': 'NPK + Magnesium',
      'Apply balanced chemical fertilizers with extra Magnesium Sulphate to combat yellowing.': 'Apply balanced chemical fertilizers with extra Magnesium Sulphate to combat yellowing.',
      'Fertilizer distributors': 'Fertilizer distributors',
      'Cultivate intercrops to improve soil health and microbial activity.': 'Cultivate intercrops to improve soil health and microbial activity.',
      'Irrigate properly during summer months.': 'Irrigate properly during summer months.',
      'Use disease-resistant seedlings for gap filling.': 'Use disease-resistant seedlings for gap filling.',
      // Leaf Spot
      'Cut and burn the severely infected lower leaves.': 'Cut and burn the severely infected lower leaves.',
      'Improve field sanitation by removing weeds.': 'Improve field sanitation by removing weeds.',
      'Mancozeb or Copper Oxychloride': 'Mancozeb or Copper Oxychloride',
      'Spray 1% Bordeaux mixture or 0.2% Mancozeb on the leaves.': 'Spray 1% Bordeaux mixture or 0.2% Mancozeb on the leaves.',
      'General agro-chemical shops': 'General agro-chemical shops',
      'Ensure adequate potassium nutrition in the soil.': 'Ensure adequate potassium nutrition in the soil.',
      'Maintain wider spacing during new planting.': 'Maintain wider spacing during new planting.',
    },
    'si': {
      'home': 'මුල් පිටුව',
      'scan': 'පරිලෝකනය (Scan)',
      'history': 'ඉතිහාසය',
      'support': 'සහාය',
      'healthy': 'නිරෝගී',
      'root_wilt': 'මුල් කුණුවීම (Root Wilt)',
      'bud_rot': 'ගොබය කුණුවීම (Bud Rot)',
      'leaf_spot': 'පත්‍ර පුල්ලි (Leaf Spot)',
      'lethal_yellowing': 'මාරාන්තික කහවීම (Lethal Yellowing)',
      'confidence': 'විශ්වාසනීයත්වය',
      'predicted_disease': 'හඳුනාගත් රෝගය',
      'detected': 'හඳුනාගත හැක',
      'no_active_plan': 'සක්‍රිය ප්‍රතිකාර සැලසුමක් නොමැත',
      'scan_leaf_start': 'රෝග හඳුනා ගැනීමට සහ ප්‍රතිකාර ආරම්භ කිරීමට පොල් පත්‍රයක් පරිලෝකනය කරන්න.',
      'scan_leaf_now': 'දැන් පරිලෝකනය කරන්න',
      'analysis_overview': 'විශ්ලේෂණ අංශය',
      'recent_scans': 'මෑත පරිලෝකන',
      'delete': 'මකන්න',
      'are_you_sure': 'ඔබට විශ්වාසද?',
      'cancel': 'අවලංගු කරන්න',
      'confirm_delete': 'මෙම වාර්තාව මකා දැමීමට අවශ්‍යද?',
      'yes': 'ඔව්',
      'app_name': 'Cocolytics',
      'greeting': 'ආයුබෝවන්',
      'change_language': 'භාෂාව වෙනස් කරන්න',
      'community': 'ප්‍රජාව',
      'ask_ai': 'AI ගෙන් අසන්න',
      'ask_cocolytics_ai': 'Cocolytics AI ගෙන් අසන්න',
      'get_ai_answer': 'AI පිළිතුර ලබා ගන්න',
      'ai_answer': 'AI පිළිතුර',
      'listen': 'අසන්න',
      'stop': 'නවත්වන්න',
      'ask_again': 'නැවත අසන්න',
      'ask_community': 'ප්‍රජාවගෙන් අසන්න',
      'post_question': 'ප්‍රශ්නයක් යොමු කරන්න',
      'post': 'පල කරන්න',
      'no_posts_yet': 'තවමත් ප්‍රකාශන නොමැත. ප්‍රජාව ආරම්භ කිරීමට ප්‍රශ්නයක් අසන්න.',
      'common_symptoms': 'පොදු රෝග ලක්ෂණ',
      'treatments': 'ප්‍රතිකාර',
      'logout': 'නික්මෙන්න',
      'botanical_name': 'උද්භිද විද්‍යාත්මක නම',
      'scientific_name': 'විද්‍යාත්මක නාමය',
      'plant_health': 'ශාක සෞඛ්‍යය',
      'no_treatment_data': 'ප්‍රතිකාර දත්ත නොමැත',
      'profile': 'පැතිකඩ',
      'home_summary': 'මෙන්න ඔබේ ගොවිපල සෞඛ්‍ය සාරාංශය',
      'total': 'එකතුව',
      'cases_in': 'රෝගීන්',
      'districts_reporting': 'දිස්ත්‍රික්ක වාර්තා වේ',
      'pending_actions': 'ඉතිරි ක්‍රියාමාර්ග',
      'steps_to_complete': 'අවසන් කිරීමට පියවර',
      'active_treatment_plan': 'සක්‍රිය ප්‍රතිකාර සැලැස්ම',
      'view_all': 'සියල්ල බලන්න',
      'steps_done': 'පියවර අවසන්',
      'complete': 'සම්පූර්ණයි',
      'what_to_do_next': 'මීළඟට කළ යුතු දේ',
      'more_steps_roadmap': 'තවත් පියවර මාර්ග සිතියමේ',
      'how_can_we_help': 'අපට ඔබට උදව් කළ හැක්කේ කෙසේද?',
      'search_topics': 'මාතෘකා, ගැටලු, ප්‍රවීණයන් සොයන්න...',
      'government_hotline': 'රජයේ ක්ෂණික ඇමතුම',
      'contact_state_agri': 'ප්‍රාන්ත කෘෂිකර්ම දෙපාර්තමේන්තුව අමතන්න',
      'expert_consultation': 'විශේෂඥ උපදේශනය',
      'chat_with_pathologists': 'ශාක රෝග විශේෂඥයන් සමඟ කතා කරන්න',
      'technical_support': 'තාක්ෂණික සහාය',
      'app_issues': 'යෙදුම් දෝෂ සහ ස්කෑනරය සැකසීම',
      'agricultural_centers': 'කෘෂිකර්ම මධ්‍යස්ථාන',
      'agri_centers_count': 'මධ්‍යස්ථාන',
      'all': 'සියල්ල',
      'short_term': 'කෙටි කාලීන විසඳුම්',
      'prevention_tips': 'නිවාරණ උපදෙස්',
      'chemical_action': 'ක්ෂණික රසායනික ක්‍රියාව',
      'long_term': 'දිගු කාලීන විසඳුම්',
      'save_plan': 'මගේ ප්‍රතිකාර සැලැස්ම ලෙස සුරකින්න',
      'view_roadmap': 'මගේ ප්‍රතිකාර මාර්ග සිතියම බලන්න',
      'use': 'භාවිතය',
      'where_to_buy': 'මිලදී ගත හැකි ස්ථාන',
      'how_to_use': 'මෙම රසායනිකය භාවිතා කරන ආකාරය',
      'replace_plan': 'පවතින සැලසුම ප්‍රතිස්ථාපනය කරනවාද?',
      'district_risk': 'දිස්ත්‍රික් අවදානම',
      'current_severity': 'වත්මන් බරපතලකම',
      'top_disease': 'ප්‍රධාන රෝගය',
      'national_stats': 'ජාතික ස්කෑන් දත්ත',
      'no_active_alerts': 'සක්‍රිය ඇඟවීම් නොමැත',
      'no_active_case': 'සක්‍රිය රෝගීන් නොමැත',
      'latest_detected': 'ආසන්නතම හඳුනාගත් මට්ටම',
      'waiting_scan': 'ස්කෑන් දත්ත සඳහා රැඳී සිටින්න',
      'no_cases_yet': 'තවමත් රෝගීන් නොමැත',
      'no_affected_districts': 'බලපෑමට ලක් වූ දිස්ත්‍රික්ක නොමැත',
      'all_clear': 'අවදානමක් නොමැත',
      // Treatments - Bud Rot
      'Immediately remove and destroy the infected bud tissues.': 'ආසාදිත ගොබ කොටස් වහාම ඉවත් කර විනාශ කරන්න.',
      'Apply Bordeaux mixture or copper oxychloride paste to the cut surface.': 'කැපූ පෘෂ්ඨයට බෝඩෝ මිශ්‍රණය හෝ කොපර් ඔක්සික්ලෝරයිඩ් තලපයක් ආලේප කරන්න.',
      'Provide good drainage to reduce humidity around the palm.': 'ගස අවට ආර්ද්‍රතාවය අඩු කිරීම සඳහා හොඳ ජලවහන පද්ධතියක් සාදන්න.',
      'Copper Oxychloride': 'කොපර් ඔක්සික්ලෝරයිඩ් (Copper Oxychloride)',
      'Apply as a paste on the affected crown or spray 1% Bordeaux mixture.': 'බලපෑමට ලක් වූ මුදුනට තලපයක් ලෙස ගාන්න, නැතහොත් 1% බෝඩෝ මිශ්‍රණය ඉසින්න.',
      'Local agricultural stores': 'ප්‍රාදේශීය කෘෂිකාර්මික වෙළඳසැල්',
      'Farm chem suppliers': 'ගොවිපල රසායන සැපයුම්කරුවන්',
      'Regularly inspect neighboring palms for early detection.': 'කලින් හඳුනා ගැනීම සඳහා අවට ගස් නිතිපතා පරීක්ෂා කරන්න.',
      'Ensure proper plant spacing for air circulation.': 'වාතාශ්‍රය ලැබීම සඳහා ගස් අතර නිසි පරතරය සහතික කරන්න.',
      'Avoid physical damage to the palm bud during harvesting.': 'අස්වනු නෙලීමේදී ගොබයට භෞතික හානි වීමෙන් වළකින්න.',
      // Lethal Yellowing
      'Quarantine the affected area immediately.': 'බලපෑමට ලක් වූ ප්‍රදේශය වහාම නිරෝධායනය කරන්න.',
      'Fell and burn actively infected palms to prevent insect vector spread.': 'කෘමීන් පැතිරීම වැළැක්වීම සඳහා ආසාදිත ගස් කපා පුළුස්සා දමන්න.',
      'Oxytetracycline HCl': 'ඔක්සිටෙට්‍රාසයික්ලින් HCl',
      'Trunk injection (antibiotic) for temporary suppression of symptoms. Note: Not a cure.': 'රෝග ලක්ෂණ තාවකාලිකව මර්දනය කිරීම සඳහා කඳට එන්නත් කිරීම (ප්‍රතිජීවක). සටහන: මෙය ස්ථිර සුවයක් නොවේ.',
      'Certified agricultural antibiotic distributors': 'සහතික කළ කෘෂිකාර්මික ප්‍රතිජීවක බෙදාහරින්නන්',
      'Replant with resistant or highly tolerant coconut varieties (e.g., Malayan Dwarf).': 'රෝගවලට ඔරොත්තු දෙන පොල් ප්‍රභේද (උදා: මැලේසියානු කුරු) නැවත වගා කරන්න.',
      'Control populations of the planthopper vector.': 'රෝග බෝ කරන කෘමි ගහනය පාලනය කරන්න.',
      // Root Wilt
      'Cut and remove severely diseased palms showing yellowing and flaccidity.': 'කහ වී දුර්වල වූ තදබල ලෙස රෝගී වූ ගස් කපා ඉවත් කරන්න.',
      'Apply organic manure (50 kg) mixed with bio-fertilizers per palm.': 'එක් ගසකට කාබනික පොහොර කිලෝ 50ක් ජීව පොහොර සමඟ මිශ්‍ර කර යොදන්න.',
      'NPK + Magnesium': 'NPK + මැග්නීසියම්',
      'Apply balanced chemical fertilizers with extra Magnesium Sulphate to combat yellowing.': 'කහ වීම වැලැක්වීමට අමතර මැග්නීසියම් සල්ෆේට් සමඟ සමතුලිත රසායනික පොහොර යොදන්න.',
      'Fertilizer distributors': 'පොහොර බෙදාහරින්නන්',
      'Cultivate intercrops to improve soil health and microbial activity.': 'පසෙහි සෞඛ්‍යය හා ක්ෂුද්‍රජීවී ක්‍රියාකාරිත්වය වැඩි දියුණු කිරීම සඳහා අතුරු භෝග වගා කරන්න.',
      'Irrigate properly during summer months.': 'වියළි කාලවලදී නිසි ලෙස ජල සම්පාදනය කරන්න.',
      'Use disease-resistant seedlings for gap filling.': 'හිඩැස් පිරවීම සඳහා රෝග වලට ඔරොත්තු දෙන පැළ භාවිතා කරන්න.',
      // Leaf Spot
      'Cut and burn the severely infected lower leaves.': 'තදබල ලෙස ආසාදිත පහළ කොළ කපා පුළුස්සා දමන්න.',
      'Improve field sanitation by removing weeds.': 'වල් පැල ඉවත් කිරීම මගින් ක්ෂේත්‍රයේ සනීපාරක්ෂාව වැඩි දියුණු කරන්න.',
      'Mancozeb or Copper Oxychloride': 'මැන්කොසෙබ් (Mancozeb) හෝ කොපර් ඔක්සික්ලෝරයිඩ්',
      'Spray 1% Bordeaux mixture or 0.2% Mancozeb on the leaves.': 'කොළ මත 1% බෝඩෝ මිශ්‍රණය හෝ 0.2% මැන්කොසෙබ් ඉසින්න.',
      'General agro-chemical shops': 'සාමාන්‍ය කෘෂි රසායනික වෙළඳසැල්',
      'Ensure adequate potassium nutrition in the soil.': 'පසෙහි ප්‍රමාණවත් පොටෑසියම් පෝෂණයක් ඇති බව සහතික කරන්න.',
      'Maintain wider spacing during new planting.': 'නව වගාවන්හිදී පුළුල් පරතරයක් පවත්වා ගන්න.'
    }
  };
}
